### PR TITLE
unfreeze execution flow

### PR DESCRIPTION
**Pull request by DenisIzmaylov**
Now when I apply `redux-thunk` and my custom middleware as a chain:
```javascript
const createStoreWithMiddleware = applyMiddleware(thunk, catchPromise)(createStore);
```
And then dispatch promise:
```javascript
export function fetchItems(folder) {
  return (dispatch, getState) => {
    return Promise((resolve, reject) => {
    // ...
    }
  };
};
```
I could not get control because `redux-thunk` doesn't continue execution flow for functions through `next()` callback:
```javascript
export default function thunkMiddleware({ dispatch, getState }) {
  return next => action =>
    typeof action === 'function' ?
      action(dispatch, getState) :
      next(action);
}
```

This PR should resolve it and we can make middleware chains in right way.

### CODE REVIEW

**Comment by DenisIzmaylov** [comment]
Up!

**Comment by gaearon** [comment]
I'm a bit confused. If you use `redux-thunk`, this:

```js
export function fetchItems(folder) {
  return (dispatch, getState) => {
    return Promise((resolve, reject) => {
    // ...
    }
  };
};
```

is _not_ how you dispatch.

This:

```js
export function fetchItems(folder) {
  return (dispatch, getState) => {
    dispatch(Promise((resolve, reject) => {
      // ...
    })
  };
};
```

is how you do it.

But I don't see you using any features provided by redux-thunk itself, so maybe you don't need redux-thunk at all:

```js
export function fetchItems(folder) {
  return Promise((resolve, reject) => {
    // ...
  });
};
```

If this doesn't make sense, let's discuss a more complete example.

**Comment by gaearon** [comment]
To clarify: there is no meaning assigned to thunk's return result. This is by design. Return value is not meant to be interpreted by another middleware. It's just a convenience.

If we dispatched return value, we'd have to place restrictions on it, but we don't want to.

**Comment by DenisIzmaylov** [comment]
The real example is about dispatching async functions which I purposed in [redux-catch-promise middlware](https://github.com/DenisIzmaylov/redux-catch-promise). When I released it as a single middleware [you said](https://twitter.com/dan_abramov/status/630687550634622977) it would be better to use both middleware together.

Original example is:
```javascript
export function fetchItems(folder) {
  return async function (dispatch, getState) => {
    await fetch(...); 
  };
}
```

**Comment by gaearon** [comment]
I'm closing for the same reason as https://github.com/gaearon/redux-thunk/pull/23#issuecomment-145363994. It's a breaking change for too many projects, and it's fundamentally different from how this current middleware works. I was wrong when I said it's better to use `thunk` in this case—this is a totally different behavior. Sorry I mislead you!

**Pull request closed without merging**
