### PR TITLE
Add UMD build

### PR DESCRIPTION
**Pull request by brenoc**
This enables to use redux-thunk with https://npmcdn.com/.

### CODE REVIEW

**Comment by brenoc** [comment]
Actually, I don't think that's useful. Too much overhead with webpack. It's simpler to just rewrite the middleware in your own code.

**Comment by gaearon** [comment]
Yeah I guess so. Man I wish ES6 was everywhere. :-(

**Comment by brenoc** [comment]
@gaearon yeah.. :(

**Comment by gaearon** [comment]
FYI, 2.x includes a UMD build.

**Pull request closed without merging**
